import image01 from '../assets/image/skill01.png';
import image02 from '../assets/image/skill02.png';
import image03 from '../assets/image/skill03.png';
// import image01 from 'https://cdn7.allevents.in/banners/ad86ad20-4ef5-11ea-9080-655b143463bb-rimg-w526-h276-gmir.jpg?v=1581662768';
// import image02 from 'https://i.pinimg.com/originals/42/29/8b/42298b88b9656ae5692b4c1cb38aa901.jpg';
// import image03 from 'https://bacp-web-live-endpoint.azureedge.net/cache/7/6/8/1/3/b/76813b49c658d7f7a44cec754753861d76cc1bf1.jpg';
const randomRate = () => {
  return Math.floor(Math.random() * 5 + 1);
};
const data = [
  {
    id: '1',
    name: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    author: 'Deborah House',
    level: 'Beginner',
    timeToStart: 'Apr 2020',
    totalHour: '1h',
    totalRate: 124,
    rate: randomRate(),
    image: image01,
  },
  {
    id: '2',
    name: 'C# Fundamentals',
    numberOfCourse: '5 course',
    author: 'Scott Jimmy',
    level: 'Beginner',
    timeToStart: 'Feb 2018',
    totalHour: '2h',
    totalRate: 12,
    rate: randomRate(),
    image: image02,
  },
  {
    id: '3',
    name: 'Managing AWS Operations',
    numberOfCourse: '5 course',
    author: 'Angular Simon',
    level: 'Beginner',
    timeToStart: 'Jan 2018',
    totalHour: '5h',
    totalRate: 412,
    rate: randomRate(),
    image: image03,
  },
  {
    id: '4',
    name: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    author: 'Allen Scott',
    level: 'Intermediate',
    timeToStart: 'Apr 2019',
    totalHour: '5h',
    totalRate: 90,
    rate: randomRate(),
    image: image03,
  },
  {
    id: '5',
    name: 'Spring: The Big Picture',
    numberOfCourse: '5 course',
    author: 'Mark Buna',
    level: 'Beginner',
    timeToStart: 'Sep 2018',
    totalHour: '4h',
    totalRate: 42,
    rate: randomRate(),
    image: image02,
  },
  {
    id: '6',
    name: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    author: 'Jim Wilson',
    level: 'Intermediate',
    timeToStart: 'Jan 2020',
    totalHour: '10h',
    totalRate: 6,
    rate: randomRate(),
    image: image01,
  },
  {
    id: '7',
    name: 'Dependency Injection in ASP.NET Core',
    numberOfCourse: '5 course',
    author: 'Joe Jim',
    level: 'Beginner',
    timeToStart: 'Feb 2020',
    totalHour: '72h',
    totalRate: 54,
    rate: randomRate(),
    image: image01,
  },
  {
    id: '8',
    name: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    author: 'Jim Cooper',
    level: 'Intermediate',
    timeToStart: 'Apr 2017',
    totalHour: '5h',
    totalRate: 912,
    rate: randomRate(),
    image: image02,
  },
  {
    id: '9',
    name: 'Python for Data Analysts',
    numberOfCourse: '10 course',
    author: 'Eugene Rooney',
    level: 'Intermediate',
    timeToStart: 'May 2020',
    totalHour: '5h',
    totalRate: 812,
    rate: randomRate(),
    image: image03,
  },
  {
    id: '10',
    name: 'Getting Started with Your First SQL Server Instance',
    numberOfCourse: '9 course',
    author: 'Kevin Hill',
    level: 'Beginner',
    timeToStart: 'Dec 2010',
    totalHour: '5h',
    totalRate: 42,
    rate: randomRate(),
    image: image03,
  },
  {
    id: '11',
    name: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    author: 'Jim Wilson',
    level: 'Intermediate',
    timeToStart: 'Jan 2020',
    totalHour: '10h',
    totalRate: 6,
    rate: randomRate(),
    image: image01,
  },
  {
    id: '12',
    name: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    author: 'Jim Cooper',
    level: 'Intermediate',
    timeToStart: 'Apr 2017',
    totalHour: '5h',
    totalRate: 912,
    rate: randomRate(),
    image: image02,
  },
  {
    id: '13',
    name: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    author: 'Deborah House',
    level: 'Beginner',
    timeToStart: 'Apr 2020',
    totalHour: '1h',
    totalRate: 124,
    rate: randomRate(),
    image: image01,
  },
  {
    id: '14',
    name: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    author: 'Allen Scott',
    level: 'Intermediate',
    timeToStart: 'Apr 2019',
    totalHour: '5h',
    totalRate: 90,
    rate: randomRate(),
    image: image03,
  },
  {
    id: '15',
    name: 'C# Fundamentals',
    numberOfCourse: '5 course',
    author: 'Scott Jimmy',
    level: 'Beginner',
    timeToStart: 'Feb 2018',
    totalHour: '2h',
    totalRate: 12,
    rate: randomRate(),
    image: image02,
  },
];
export default data;
