// import image01 from '../assets/image/skill01.png';
// import image02 from '../assets/image/skill02.png';
// import image03 from '../assets/image/skill03.png';
const image01 =
  'https://cdn7.allevents.in/banners/ad86ad20-4ef5-11ea-9080-655b143463bb-rimg-w526-h276-gmir.jpg?v=1581662768';
const image02 =
  'https://i.pinimg.com/originals/42/29/8b/42298b88b9656ae5692b4c1cb38aa901.jpg';
const image03 =
  'https://bacp-web-live-endpoint.azureedge.net/cache/7/6/8/1/3/b/76813b49c658d7f7a44cec754753861d76cc1bf1.jpg';
const randomRate = () => {
  return Math.floor(Math.random() * 5 + 1);
};
const data = [
  {
    id: '1',
    title: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    name: 'Deborah House',
    level: 'Beginner',
    updatedAt: 'Apr 2020',
    totalHours: '1h',
    ratedNumber: 124,
    soldNumber: randomRate(),
    imageUrl: image01,
    price: 0,
  },
  {
    id: '2',
    title: 'C# Fundamentals',
    numberOfCourse: '5 course',
    name: 'Scott Jimmy',
    level: 'Beginner',
    updatedAt: 'Feb 2018',
    totalHours: '2h',
    ratedNumber: 12,
    soldNumber: randomRate(),
    imageUrl: image02,
    price: 0,
  },
  {
    id: '3',
    title: 'Managing AWS Operations',
    numberOfCourse: '5 course',
    name: 'Angular Simon',
    level: 'Beginner',
    updatedAt: 'Jan 2018',
    totalHours: '5h',
    ratedNumber: 412,
    soldNumber: randomRate(),
    imageUrl: image03,
    price: 0,
  },
  {
    id: '4',
    title: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    name: 'Allen Scott',
    level: 'Intermediate',
    updatedAt: 'Apr 2019',
    totalHours: '5h',
    ratedNumber: 90,
    soldNumber: randomRate(),
    imageUrl: image03,
    price: 0,
  },
  {
    id: '5',
    title: 'Spring: The Big Picture',
    numberOfCourse: '5 course',
    name: 'Mark Buna',
    level: 'Beginner',
    updatedAt: 'Sep 2018',
    totalHours: '4h',
    ratedNumber: 42,
    soldNumber: randomRate(),
    imageUrl: image02,
    price: 0,
  },
  {
    id: '6',
    title: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    name: 'Jim Wilson',
    level: 'Intermediate',
    updatedAt: 'Jan 2020',
    totalHours: '10h',
    ratedNumber: 6,
    soldNumber: randomRate(),
    imageUrl: image01,
    price: 0,
  },
  {
    id: '7',
    title: 'Dependency Injection in ASP.NET Core',
    numberOfCourse: '5 course',
    name: 'Joe Jim',
    level: 'Beginner',
    updatedAt: 'Feb 2020',
    totalHours: '72h',
    ratedNumber: 54,
    soldNumber: randomRate(),
    imageUrl: image01,
    price: 0,
  },
  {
    id: '8',
    title: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    name: 'Jim Cooper',
    level: 'Intermediate',
    updatedAt: 'Apr 2017',
    totalHours: '5h',
    ratedNumber: 912,
    soldNumber: randomRate(),
    imageUrl: image02,
    price: 0,
  },
  {
    id: '9',
    title: 'Python for Data Analysts',
    numberOfCourse: '10 course',
    name: 'Eugene Rooney',
    level: 'Intermediate',
    updatedAt: 'May 2020',
    totalHours: '5h',
    ratedNumber: 812,
    soldNumber: randomRate(),
    imageUrl: image03,
    price: 0,
  },
  {
    id: '10',
    title: 'Getting Started with Your First SQL Server Instance',
    numberOfCourse: '9 course',
    name: 'Kevin Hill',
    level: 'Beginner',
    updatedAt: 'Dec 2010',
    totalHours: '5h',
    ratedNumber: 42,
    soldNumber: randomRate(),
    imageUrl: image03,
    price: 0,
  },
  {
    id: '11',
    title: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    name: 'Jim Wilson',
    level: 'Intermediate',
    updatedAt: 'Jan 2020',
    totalHours: '10h',
    ratedNumber: 6,
    soldNumber: randomRate(),
    imageUrl: image01,
    price: 0,
  },
  {
    id: '12',
    title: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    name: 'Jim Cooper',
    level: 'Intermediate',
    updatedAt: 'Apr 2017',
    totalHours: '5h',
    ratedNumber: 912,
    soldNumber: randomRate(),
    imageUrl: image02,
    price: 0,
  },
  {
    id: '13',
    title: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    name: 'Deborah House',
    level: 'Beginner',
    updatedAt: 'Apr 2020',
    totalHours: '1h',
    ratedNumber: 124,
    soldNumber: randomRate(),
    imageUrl: image01,
    price: 0,
  },
  {
    id: '14',
    title: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    name: 'Allen Scott',
    level: 'Intermediate',
    updatedAt: 'Apr 2019',
    totalHours: '5h',
    ratedNumber: 90,
    soldNumber: randomRate(),
    imageUrl: image03,
    price: 0,
  },
  {
    id: '15',
    title: 'C# Fundamentals',
    numberOfCourse: '5 course',
    name: 'Scott Jimmy',
    level: 'Beginner',
    updatedAt: 'Feb 2018',
    totalHours: '2h',
    ratedNumber: 12,
    soldNumber: randomRate(),
    imageUrl: image02,
    price: 0,
  },
];
export default data;
