const vn = {
  student: 'Học viên',
  rating: 'Đánh giá',
  oldPass: 'Mật khẩu cũ',
  newPass: 'Mật khẩu mới',
  showPass: 'Hiện mật khẩu',
  hour: 'giờ',
  enrolled: 'học viên',
  updated: 'Cập nhật',
  course: 'Khoá học',
  lesson: 'Bài học',
  free: 'Miễn phí',
  intro: 'Giới thiệu',
  skill: 'Kĩ năng',
  taughtBy: 'Các khoá học được dạy bởi',

  homeTitle: 'Trang Chủ',
  homeRecommend: 'Gợi ý cho bạn',
  homeCategories: 'Danh mục',
  homeBestSeller: 'Bán chạy',
  homeRating: 'Thịnh hành',
  homeNewRelease: 'Mới phát hành',
  homeTopAuthor: 'Tác giả hàng đầu',

  myCourseTitle: 'Khoá học của tôi',
  myCourseStart: 'Bắt đầu Khoá học',
  myCourseComplete: 'Hoàn thành',

  favoriteTitle: 'Yêu thích',

  searchTitle: 'Tím kiếm',
  searchHear: 'Tìm kiếm ở đây',
  searchRecent: 'Lịch sử tìm kiếm',
  searchAll: 'Tất cả',
  searchCourse: 'Khoá học',
  searchAuthor: 'Tác giả',
  searchResult: 'Kết Quả',
  searchErr: 'Không tìm thấy kết quả',
  searchTry: 'Thử lại sau',

  settingTitle: 'Cài đặt',
  settingDarkMode: 'Chế độ bóng đêm',
  settingFeedBack: 'Gởi phản hồi',
  settingLanguage: 'Endlish',
  settingContact: 'LIên hệ',
  settingVersion: 'Phiên bản',
  settingAbout: 'Về chúng tôi',
  settingLogout: 'Đăng xuất',

  profileTitle: 'Tài khoản',
  profileSetting: 'Cài đặt tài khoản',
  profileUpdate: 'Cập nhật tài khoản',
  profilePassword: 'Đổi mật khẩu',
  profileCate: 'Cập nhật danh mục yêu thích',
  profileOtherSetting: 'Cài đặt khác',

  detailContinue: 'Tiếp tục',
  detailJohn: 'Tham gia',
  detailLike: 'Yêu thích',
  detailLiked: 'Đã thích',
  detailNotRequire: 'Không yêu cầu',
  detailWhatLearn: 'Bạn sẽ học được',
  detailRequire: 'Yêu cầu',
  detailDescription: 'Mô tả',
  detailSame: 'Các khoá học liên quan',
  detailCreated: 'Được dạy bởi',
  detailProfile: 'Xem trang cá nhân',
  detailStudent: 'Phản hồi của học sinh',
  detailAllFeed: 'Xem tất cả phản hồi',
  detailCurriculum: 'Danh sách bài giảng',
  detailAverage: 'Đánh giá trung bình',

  feedback: 'Viết đánh giá của bạn',
  feedbackYour: 'Your Feedback',
  feedbackContent: 'Nội dung',
  feedbackPresent: 'Truyền đạt',
  feedbackFormal: 'Hình thức',
  feedbackSubmit: 'Gởi phản hồi',

  lessonLecture: 'Bài giảng',
  lessonNote: 'Ghi chú',
  lessonExercise: 'Bài tập',
  lessonMore: 'Thêm',
  lessonIns: 'Giảng viên',
  lessonResponse: 'Phản hồi',
  lessonNoResponse: 'Không ',
  lessonForum: 'Diễn đàn câu hỏi',
  lessonAddQues: 'Thêm câu hỏi',
  lessonAns: 'Trả lời',
  lessonDownload: 'Tải khoá học',
  lessonShare: 'Chi sẻ khoá học',
  lessonResource: 'Tài liệu',
  lessonAddFav: 'Thêm vào yêu thích',
  lessonReFav: 'Xoá khỏi yêu thích',
};

const en = {
  homeTitle: 'Home',
  homeRecommend: 'Recommended For You',
  homeCategories: 'Categories',
  homeBestSeller: 'Best Seller',
  homeRating: 'Top Rating',
  homeNewRelease: 'New Releases',
  homeTopAuthor: 'Top Authors',

  myCourseTitle: 'My Courses',
  myCourseStart: 'Start Course',
  myCourseComplete: 'Completed',

  favoriteTitle: 'Favorite',

  searchTitle: 'Search',
  searchHear: 'Search here...',
  searchRecent: 'Recent searches',
  searchAll: 'All',
  searchCourse: 'Courses',
  searchAuthor: 'Author',
  searchResult: 'results',
  searchErr: 'No Matching Courses',
  searchTry: 'Try another one',

  settingTitle: 'Settings',
  settingDarkMode: 'Dark Mode',
  settingFeedBack: 'Send feedback',
  settingLanguage: 'Tiếng việt',
  settingContact: 'Contact support',
  settingVersion: 'App version',
  settingAbout: 'About us',
  settingLogout: 'Logout',

  student: 'students',
  rating: 'Rating',
  name: 'Name',
  phoneNumber: 'Phone Number',
  oldPass: 'Old Password',
  newPass: 'New Password',
  showPass: 'Show Password',
  hour: 'hours',
  enrolled: 'Enrolled',
  updated: 'Updated',
  course: 'Course',
  lesson: 'Lesson',
  free: 'Free',
  intro: 'Introduction',
  skill: 'Skills',
  taughtBy: 'Courses taught by',

  profileTitle: 'Profile',
  profileSetting: 'Account Settings',
  profileUpdate: 'Update Profile',
  profilePassword: 'Change Password',
  profileCate: 'Update Your Favorite Categories',
  profileOtherSetting: 'Other Settings',

  detailContinue: 'Continue',
  detailJohn: 'John now',
  detailLike: 'Like',
  detailLiked: 'Liked',
  detailWhatLearn: 'What will you learn',
  detailNotRequire: 'Not required',
  detailRequire: 'Requirements',
  detailDescription: 'Description',
  detailSame: 'The same Topic',
  detailCreated: 'Created by',
  detailProfile: 'View profile',
  detailStudent: 'Student Feedback',
  detailAllFeed: 'See All Feedback',
  detailCurriculum: 'Curriculum',
  detailAverage: 'Average rating',
  feedback: 'Write your feedback',
  feedbackYour: 'Your Feedback',
  feedbackContent: 'Your Feedback',
  feedbackPresent: 'Presentation',
  feedbackFormal: 'Formality',
  feedbackSubmit: 'Submit',

  lessonLecture: 'Lecture',
  lessonNote: 'Note',
  lessonExercise: 'Exercise',
  lessonMore: 'More',
  lessonIns: 'Instructor',
  lessonResponse: 'Response',
  lessonNoResponse: 'No',
  lessonForum: 'Forum Question',
  lessonAddQues: 'Add Question',
  lessonAns: 'Answer',
  lessonDownload: 'Download course',
  lessonShare: 'Share Course',
  lessonResource: 'Resources',
  lessonAddFav: 'Add course to favorite',
  lessonReFav: 'Remove course from favorite',
};

export {vn, en};
