const image01 =
  'https://storage.googleapis.com/itedu-bucket/Courses/9f3d46fa-61d2-4d4c-a392-a8e79ca7f335/avatar/67a2008d-7f04-4240-bbfc-1182c4f052af.jpg';
const image02 =
  'https://storage.googleapis.com/itedu-bucket/Courses/24b1856a-953c-419b-84c5-a9ef44bc139e/avatar/0d738acf-88c4-47cc-b7c7-329ad7ae57da.png';
const image03 =
  'https://storage.googleapis.com/itedu-bucket/Courses/9f3d46fa-61d2-4d4c-a392-a8e79ca7f335/avatar/67a2008d-7f04-4240-bbfc-1182c4f052af.jpg';
const randomRate = () => {
  return Math.floor(Math.random() * 5 + 1);
};
const data = [
  {
    id: '1',
    title: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    name: 'Deborah House',
    level: 'Beginner',
    updatedAt: 'Apr 2020',
    totalHours: '1h',
    ratedNumber: 124,
    soldNumber: randomRate(),
    imageUrl: image01,
  },
  {
    id: '2',
    title: 'C# Fundamentals',
    numberOfCourse: '5 course',
    name: 'Scott Jimmy',
    level: 'Beginner',
    updatedAt: 'Feb 2018',
    totalHours: '2h',
    ratedNumber: 12,
    soldNumber: randomRate(),
    imageUrl: image02,
  },
  {
    id: '3',
    title: 'Managing AWS Operations',
    numberOfCourse: '5 course',
    name: 'Angular Simon',
    level: 'Beginner',
    updatedAt: 'Jan 2018',
    totalHours: '5h',
    ratedNumber: 412,
    soldNumber: randomRate(),
    imageUrl: image03,
  },
  {
    id: '4',
    title: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    name: 'Allen Scott',
    level: 'Intermediate',
    updatedAt: 'Apr 2019',
    totalHours: '5h',
    ratedNumber: 90,
    soldNumber: randomRate(),
    imageUrl: image03,
  },
  {
    id: '5',
    title: 'Spring: The Big Picture',
    numberOfCourse: '5 course',
    name: 'Mark Buna',
    level: 'Beginner',
    updatedAt: 'Sep 2018',
    totalHours: '4h',
    ratedNumber: 42,
    soldNumber: randomRate(),
    imageUrl: image02,
  },
  {
    id: '6',
    title: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    name: 'Jim Wilson',
    level: 'Intermediate',
    updatedAt: 'Jan 2020',
    totalHours: '10h',
    ratedNumber: 6,
    soldNumber: randomRate(),
    imageUrl: image01,
  },
  {
    id: '7',
    title: 'Dependency Injection in ASP.NET Core',
    numberOfCourse: '5 course',
    name: 'Joe Jim',
    level: 'Beginner',
    updatedAt: 'Feb 2020',
    totalHours: '72h',
    ratedNumber: 54,
    soldNumber: randomRate(),
    imageUrl: image01,
  },
  {
    id: '8',
    title: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    name: 'Jim Cooper',
    level: 'Intermediate',
    updatedAt: 'Apr 2017',
    totalHours: '5h',
    ratedNumber: 912,
    soldNumber: randomRate(),
    imageUrl: image02,
  },
  {
    id: '9',
    title: 'Python for Data Analysts',
    numberOfCourse: '10 course',
    name: 'Eugene Rooney',
    level: 'Intermediate',
    updatedAt: 'May 2020',
    totalHours: '5h',
    ratedNumber: 812,
    soldNumber: randomRate(),
    imageUrl: image03,
  },
  {
    id: '10',
    title: 'Getting Started with Your First SQL Server Instance',
    numberOfCourse: '9 course',
    name: 'Kevin Hill',
    level: 'Beginner',
    updatedAt: 'Dec 2010',
    totalHours: '5h',
    ratedNumber: 42,
    soldNumber: randomRate(),
    imageUrl: image03,
  },
  {
    id: '11',
    title: 'Domain-Driven Design',
    numberOfCourse: '5 course',
    name: 'Jim Wilson',
    level: 'Intermediate',
    updatedAt: 'Jan 2020',
    totalHours: '10h',
    ratedNumber: 6,
    soldNumber: randomRate(),
    imageUrl: image01,
  },
  {
    id: '12',
    title: 'Building Application with React and Flux',
    numberOfCourse: '5 course',
    name: 'Jim Cooper',
    level: 'Intermediate',
    updatedAt: 'Apr 2017',
    totalHours: '5h',
    ratedNumber: 912,
    soldNumber: randomRate(),
    imageUrl: image02,
  },
  {
    id: '13',
    title: 'Angular Fundamentals',
    numberOfCourse: '5 course',
    name: 'Deborah House',
    level: 'Beginner',
    updatedAt: 'Apr 2020',
    totalHours: '1h',
    ratedNumber: 124,
    soldNumber: randomRate(),
    imageUrl: image01,
  },
  {
    id: '14',
    title: 'Spring Framework: Spring MVC Fundamentals',
    numberOfCourse: '5 course',
    name: 'Allen Scott',
    level: 'Intermediate',
    updatedAt: 'Apr 2019',
    totalHours: '5h',
    ratedNumber: 90,
    soldNumber: randomRate(),
    imageUrl: image03,
  },
  {
    id: '15',
    title: 'C# Fundamentals',
    numberOfCourse: '5 course',
    name: 'Scott Jimmy',
    level: 'Beginner',
    updatedAt: 'Feb 2018',
    totalHours: '2h',
    ratedNumber: 12,
    soldNumber: randomRate(),
    imageUrl: image02,
  },
];

export const listCourseProvider = async () => {
  return data;
};

export const findCourseProvider = async (id) => {
  return data.find((item) => item.id === id);
};
